### Scalar
- Scalares are just one numeric values
- lower-cased letter as notation e.x. x, y, z
-  all continuous real-valued Scalars R
-  $x \in  R$ , means: x is a real-values scalar. The symbole means "in"
-  $x, y \in  {0,1}$ 

In [1]:
!pip install torch

Looking in indexes: https://int.repositories.cloud.sap/artifactory/api/pypi/build-releases-pypi/simple, https://int.repositories.cloud.sap/artifactory/api/pypi/build-milestones-pypi/simple


In [2]:
import torch
x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

### Vecotrs
- list of scalar values.
- named elements, entries or components of the vector.
- e.x. loan defaults prediction represented as vector with income, length of employment and number of previous defaults as its components.
- vectors denoted as bold-faced, lower-cased letters (e.g., :math:`\mathbf{x}`,
:math:`\mathbf{y}`, and :math:`\mathbf{z})`

In [3]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [5]:
x[3]

tensor(3)

### Length, Dimensionality, and shape
- length of vector is commonly called dimension of a vector
- access lenght by len function in python 
- access lenght by len function in python or shape in pytorch

In [6]:
len(x)

4

In [7]:
x.shape

torch.Size([4])

### Matrices
- vectors generlize scalars from order zero to order one, matrices generlize vectors from order one to order two.
- denoted with bald-faced, capital letters 
- represented in code as tensors with two axes.
- m rows and n columns of real-valued scalars.
- shape is (m x n) 
- matrix with same number of rows and columns is squared matrix
- A *transpose* means  exchage rows and columns.
- if B = A *transpose*, tehn bij = aji for any i and j
- A: is symetric matrix if it is sqaure matrix and A = *A transpose*

In [8]:
A = torch.arange(20).reshape(5, 4); A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [9]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [11]:
B = torch.tensor([[1, 2, 3], [2,0,4], [3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [12]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

### Tensors
- here: refers to algebraic objects
- n-dimensional arrays with arbitrary number of axes.
- vectors are first order, matrces and tensors are second order
-  denoted with capital lettters of special font face
-  indexing mechanism is similar to that of metrices.

In [13]:
X = torch.arange(24).reshape(2,3,4); X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

### Basic Properties of Tensor Arithmetic
- any elementwise unary operation does not change the shape of its operand.
- binary elementwise operation on any two tensors of the same shape, will result a tensor of that same shape e.x., add two matrecies
- Hadamard Product is elementwise multiplication of two metrecies, denoted as circle with point in the center.

- Mulitply or add a scalar will not change the shape of the tensor

In [41]:
A = torch.arange(20, dtype=torch.float32).reshape(5,4)
B = A.clone() # Assign a copy of 'A' to 'B' by allocating new memory
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [23]:
A * B # Hadamard Product: [a11b11 a12b12 .... a1nb1n 
                          
                                         #]

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [24]:
a = 2 
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

### Reduction
- some of elements of a tensor
- symbole is :math:`\sum`
- can also be used to sum element of matrx of size (m, n)
- by default, sum reduces a tensor along all its axes to a scalar
- one can specifiy the axes along which the tensor is reduced via summation.
- dimension is lost. e.x, (3,2), sum along axes = 0, results in a tensor with a vector of shape 2 (3 is lost, axes = 0)

In [25]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum() # reduction

(tensor([0., 1., 2., 3.]), tensor(6.))

In [26]:
A.shape, A.sum()

(torch.Size([5, 4]), tensor(190.))

In [27]:
# shape of A (5, 4)
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape # axes =0 , which is 5 is lost, we have vector of 4

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [28]:
# axis=1, 4 is lost, result vector of shape 5
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

### None-Reduction Sum
- keeps number axes non changed e.i., array of shape (3,2): sum it a long the axis=1, but keep it 3 rows and 1 columen(sum of the 2 other columns). With the normal reduction u will get a vector with a size of 3. Dimension is not lost
-  we can use broadcasting to divide the original method and the new one (after we used non-reduction sum)
-  cumsum will not change the axis. If one performed cumsum along zero-axis, each row is the sum of the previous rows

In [29]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [30]:
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [ ]:
A.cumsum(axis=0)

### 2.3.7 Dot Products
- sum of the elementwise multiplications
-  if we have a vector x and we multiply it with a wieght vector w. if the weights are not negative and sum to one, the dot product express a weighted average.
-  After normlizing the two  vectors to have a unit length, the dot product express the cosine of the angle between them.

In [31]:
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [32]:
torch.sum(x * y) # same as above sum of element-wise multiplication

tensor(6.)

### 2.3.8. Matrix-Vector Products
- is a column vector
- we can represent rotations as multiplications by a square matrix.
- use matrix-vector mulitplication to describe the most intensive calculations 
 required when computing each layer in a neural network given the values of the previous layer

In [33]:
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

### 2.3.9 Matrix-Matrix Multiplication
- think of it as performing m matrix-vector products and stitching the results together 

In [34]:
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

### 2.3.10 Norms
-  informally, norm of a vector tells us how big the vector is (size not dimensionality, rather the magnitude of the components).
-  it is a function that maps a vector to a scaler, satisfying a handful of properties:
		- if we scale all elements of a vector by a constant factor, its norm also scales by the absolute value of the same constant factor.
		- traingle inequality: f(x+y) <= f(x) + f(y)
		- norm must be non-negative (least size is zero)
		- smallest norm (zero) is only achieved by a vector cosisting of all zeros.
		- Euclidian distance is the L2 norm
		- L1 norm is the sum of the absolute values of the vector elements.
		- L1 is less influnced by outliers.
		- L1 & L2 are casses of Lp norm
		-  Analogous to L2 norms of vectors, the Frobenius norm of a matrix is the sum of the sqaures of the matrix elments
		-  The forbenius norm satisfy the property of a vector norm. It is like L2 norm for matrix-shaped vector

In [35]:
u = torch.tensor([3.0, -4.0])
torch.norm(u) # L2 norm

tensor(5.)

In [ ]:
torch.abs(u).sum() # L1 norm some of the absolute values of the vector elements

In [36]:
torch.norm(torch.ones((4, 9))) # Forbenius norm, as L2 norm for Matrix-shaped vector

tensor(6.)

### Summary
Scalars, vectors, matrices, and tensors are basic mathematical objects in linear algebra.

Vectors generalize scalars, and matrices generalize vectors.

Scalars, vectors, matrices, and tensors have zero, one, two, and an arbitrary number of axes, respectively.

A tensor can be reduced along the specified axes by sum and mean.

Elementwise multiplication of two matrices is called their Hadamard product. It is different from matrix multiplication.

In deep learning, we often work with norms such as the  norm, the  norm, and the Frobenius norm.

We can perform a variety of operations over scalars, vectors, matrices, and tensors.

In [37]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [42]:
print(A == (A.T).T) # transpose of A-transpose is A

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [43]:
# given two matrices A and B, proof that the sum of the transposes is the same as the transpose of the sum
print((A.T + B.T) == (A + B).T)

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])


In [46]:
len(X) # X is a tensor and the output will be the first dimension

2

In [52]:
X1 = torch.arange(50).reshape(5, 5, 2)
len(X1) # X is a tensor and the output will be the first dimension

5

In [58]:
A / A.sum(axis=1) 
# error, cuz we summed the  along axis 1, si we endup with a vector of 
#size 5(nr. of rows) and we try to divde matrix with 4 column with a vector of 5 elments
# if we use this A/ A.sum(axis= 0) or we only have a scaler (singelton), it will work

RuntimeError: The size of tensor a (4) must match the size of tensor b (5) at non-singleton dimension 1

In [60]:
#analysis
print( "shape:2", A.shape)
print(A.sum(axis=0))

shape:2 torch.Size([5, 4])
tensor([40., 45., 50., 55.])


In [61]:
A.sum(axis=1)

tensor([ 6., 22., 38., 54., 70.])

In [ ]:
#7 when travelling between two points in Manhatten, what is the distance that you 
# would cover in term of the coordiante, i.e., in terms of avenues and streets? can you travel diagonally?
# one can go up, down, right, left, but no diagonal directions are allowed

In [64]:
X2 = torch.arange(24, dtype=torch.float32).reshape(2,3, 4)

In [65]:
torch.norm(X2)

tensor(65.7571)